### ISSUE TITLE
Problem after upgrading packages 

### ISSUE THREAD

**Issue by mx12mx12** [influxdata/influxdb#22004]
Hello, 
unfortunately I'm from the construction industry. But for a while now, I had an influx database to manage sensors data in the building. I am a complete beginner. Everything worked fine for 2 years. Today, after updating packages in raspbian influx it does not work. I have messages: 
Failed to connect to http://localhost:8086: Get http://localhost:8086/ping: dial tcp [::1]:8086: connect: connection refused
Please check your connection settings and ensure 'influxd' is running.

After `sudo systemctl start influxdb` is
Job for influxdb.service failed because the control process exited with error code.
See "systemctl status influxdb.service" and "journalctl -xe" for details.

And after `systemctl status influxdb.service` i have:
● influxdb.service - InfluxDB is an open-source, distributed, time series database
   Loaded: loaded (/lib/systemd/system/influxdb.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2021-08-01 23:11:23 CEST; 1min 12s ago
     Docs: https://docs.influxdata.com/influxdb/
  Process: 981 ExecStart=/usr/lib/influxdb/scripts/influxd-systemd-start.sh (code=exited, status=203/EXEC)

sie 01 23:11:23 raspberrypi systemd[1]: influxdb.service: Service RestartSec=100ms expired, scheduling restart.
sie 01 23:11:23 raspberrypi systemd[1]: influxdb.service: Scheduled restart job, restart counter is at 5.
sie 01 23:11:23 raspberrypi systemd[1]: Stopped InfluxDB is an open-source, distributed, time series database.
sie 01 23:11:23 raspberrypi systemd[1]: influxdb.service: Start request repeated too quickly.
sie 01 23:11:23 raspberrypi systemd[1]: influxdb.service: Failed with result 'exit-code'.
sie 01 23:11:23 raspberrypi systemd[1]: Failed to start InfluxDB is an open-source, distributed, time series database.

What happend, can you help me?

kind regards Michal

**Comment by twm** [comment]
I'm seeing the same issue on an Ubuntu 21.04 system. If we look at the journald logs for influx.service I see this error message:

```
❯ journalctl -u influxdb --since '30 minutes ago'
-- Logs begin at Fri 2021-07-16 06:23:01 PDT, end at Sun 2021-08-01 15:58:27 PDT. --
...
Aug 01 15:34:19 aorist systemd[1]: Starting InfluxDB is an open-source, distributed, time series database...
Aug 01 15:34:19 aorist systemd[14270]: influxdb.service: Failed to execute command: Permission denied
Aug 01 15:34:19 aorist systemd[14270]: influxdb.service: Failed at step EXEC spawning /usr/lib/influxdb/scripts/influxd-systemd-start.sh: Permission denied
Aug 01 15:34:19 aorist systemd[1]: influxdb.service: Control process exited, code=exited, status=203/EXEC
Aug 01 15:34:19 aorist systemd[1]: influxdb.service: Failed with result 'exit-code'.
...
```

This looks like a bug in the packaging; the `influxd-systemd-start.sh` script is only executable by root:

```
 ll /usr/lib/influxdb/scripts/
total 16
drwxr-xr-x 1 root root   94 Aug  1 11:48 ./
drwxr-xr-x 1 root root   14 Jul  5 22:30 ../
-rw-r--r-- 1 root root  533 Jul 21 12:55 influxdb.service
-rwxr--r-- 1 root root  520 Jul 21 12:55 influxd-systemd-start.sh*
-rw-r--r-- 1 root root 5702 Jul 21 12:55 init.sh
```

However, if we look at the `influxdb.service` unit we can see that it will run as the `influxdb` user:

```
 ❯ systemctl cat influxdb.service
# /lib/systemd/system/influxdb.service
# If you modify this, please also make sure to edit init.sh

[Unit]
Description=InfluxDB is an open-source, distributed, time series database
Documentation=https://docs.influxdata.com/influxdb/
After=network-online.target

[Service]
User=influxdb
Group=influxdb
LimitNOFILE=65536
EnvironmentFile=-/etc/default/influxdb
ExecStart=/usr/lib/influxdb/scripts/influxd-systemd-start.sh
KillMode=control-group
Restart=on-failure
Type=forking
PIDFile=/var/lib/influxdb/influxd.pid

[Install]
WantedBy=multi-user.target
Alias=influxd.service
```

I have worked around this for the moment by the startup script world-executable:

```
sudo chmod +x /usr/lib/influxdb/scripts/influxd-systemd-start.sh
```

**Comment by twm** [comment]
This appears to trace back to https://github.com/influxdata/influxdb/pull/21850

That PR can also cause startup of the systemd unit to time out (e.g. it does so on my system when starting from a cold disk cache, as on reboot). You can increase the startup timeout with the command `sudo systemctl edit influxdb.service`. Enter content like this:

```
[Service]
TimeoutStartSec=5min
```

See [systemd.service(5)](https://www.freedesktop.org/software/systemd/man/systemd.service.html) for information on `TimeoutStartSec`.

**Comment by twm** [comment]
See also https://github.com/influxdata/influxdb/issues/21967

**Comment by codyshepherd** [comment]
This issue is addressed by #21987, and a v1.8.8 release with the fix will be published today.

**Comment by mx12mx12** [comment]
@codyshepherd 
Please tell me if the update is published and will it be updated when you upgrade packages in linux (sudo apt upgrade)?

**Comment by deepak18** [comment]
+1
@codyshepherd Do you see the Influx team publishing the latest tag v1.8.8 build anytime soon?

**Comment by codyshepherd** [comment]
@mx12mx12 @deepak18 Hiya, we ended up bumping the next 1.8 release to 1.8.9, which was [released today](https://github.com/influxdata/influxdb/releases/tag/v1.8.9). 

I'll check up on our plans to host older versions in the apt repo. Fwiw, although I realize this is not the same thing, older versions of our packages are available at dl.influxdata.com, e.g. http://dl.influxdata.com/influxdb/releases/influxdb_1.8.7_amd64.deb .

**Comment by AnKloss** [comment]
Hello
before i run 1.8.6.1 for last 5 months and influd start normal,  Then is show up 1.8.7.1 (10 days a go ) and influxd not start normal (Permission denied) , so i have to use sudo influx in a terminal and the is run as long the terminal is open.
Today i see 1.8.9.1 is publish and i update/upgrade , but influxd still not run as before , only with sude Influxd.
Possible to fix it ?
mfg
Andreas

**Comment by AnKloss** [comment]
2021-08-06T02:07:25.599245Z     info    InfluxDB starting       {"log_id": "0VnJHucl000", "version": "1.8.9", "branch": "1.8", "commit": "d9b56321d579"}
2021-08-06T02:07:25.599355Z     info    Go runtime      {"log_id": "0VnJHucl000", "version": "go1.13.8", "maxprocs": 4}
2021-08-06T02:07:25.701481Z     info    Using data dir  {"log_id": "0VnJHucl000", "service": "store", "path": "/var/lib/influxdb/data"}
2021-08-06T02:07:25.701662Z     info    Compaction settings     {"log_id": "0VnJHucl000", "service": "store", "max_concurrent_compactions": 2, "throughput_bytes_per_second": 50331648, "throughput_bytes_per_second_burst": 50331648}
2021-08-06T02:07:25.701755Z     info    Open store (start)      {"log_id": "0VnJHucl000", "service": "store", "trace_id": "0VnJHv1G000", "op_name": "tsdb_open", "op_event": "start"}
2021-08-06T02:07:25.702075Z     info    Open store (end)        {"log_id": "0VnJHucl000", "service": "store", "trace_id": "0VnJHv1G000", "op_name": "tsdb_open", "op_event": "end", "op_elapsed": "0.327ms"}
run: open server: open tsdb store: mkdir /var/lib/influxdb/data/_internal/_series: permission denied

**Comment by bondskin** [comment]
Running on raspbian raspberrypidns 5.10.52-v8+ #1441 SMP PREEMPT Tue Aug 3 18:14:03 BST 2021 aarch64 GNU/Linux

even with 1.8.9 the influxdb does still not come up

**Comment by AnKloss** [comment]
This help temp.  open terminal , then sudo influxd
but do not close it 
 
![27087](https://user-images.githubusercontent.com/85149594/128596070-0321a4d1-443f-4a7b-a912-5cb577191609.jpg)

**Comment by underdog** [comment]
> This help temp. open terminal , then sudo influxd
> but do not close it
> 
> ![27087](https://user-images.githubusercontent.com/85149594/128596070-0321a4d1-443f-4a7b-a912-5cb577191609.jpg)

you could start a screen session, that way you don't have to have the UI open

you could then attach/detach from it remotely also
In case you aren't familiar with screen
install screen (if it's not, apt install screen)
from command prompt, logged in as the influxdb user, type "screen"
now, execute the bash script
hit CTRL-A then d (this will drop you out of the screen session)
to reattach type "screen -rd", you can do this from a terminal window or an ssh session 

you could also run it under a tmux session.  the detach for tmux is CTRL-B d
then tmux attach-session will reattach it

**Comment by underdog** [comment]
just when i think maybe I can run influx under a screen session...it just starts crashing also

sometimes it runs fine for a long time....then dumps...then I start it and it crashes immediately

**Comment by underdog** [comment]
maxattempts change didn't fix it
still crashing

**Comment by kressnerd** [comment]
> maxattempts change didn't fix it

It fixed it for 4 different installations for Raspberry Pis. I guess with similar limited hardware it might be feasible solution as also suggested above.

> still crashing

Could you give some more details from the log, please?

**Comment by bondskin** [comment]
> sudo influxd



> This help temp. open terminal , then sudo influxd
> but do not close it
> 
> ![27087](https://user-images.githubusercontent.com/85149594/128596070-0321a4d1-443f-4a7b-a912-5cb577191609.jpg)

Hi @underdog , "sudo Influxd" does not help here.
error:
run: open server: listen: listen tcp 127.0.0.1:8088: bind: address already in use

trying to start influx returns error:
Failed to connect to http://localhost:8086: Get http://localhost:8086/ping: dial tcp [::1]:8086: connect: connection refused

**Comment by bondskin** [comment]
Just found a comment at [https://community.influxdata.com/t/influxdb-1-8-7-will-not-start/20965/24](url)

this workaround works for me
Turns out my DB is too big and it takes longer to start than the 10 seconds influxdb expects to take and so the start script aborts the process
Workaround:
Open /usr/lib/influxdb/scripts/influxd-systemd-start.sh
either comment out line 34 (exit 1) – < this is a bad idea in the long run but will allow you to test if it works

**Comment by codyshepherd** [comment]
An rc (release candidate) for 1.8.10 has been built today with further fixes for this issue: https://s3.amazonaws.com/dl.influxdata.com/influxdb/releases/influxdb_1.8.10rc0_amd64.deb

**Comment by bijwaard** [comment]
> Workaround:
> Open /usr/lib/influxdb/scripts/influxd-systemd-start.sh
> either comment out line 34 (exit 1) – < this is a bad idea in the long run but will allow you to test if it works

Guess it would be better to either increase the 1-second sleep on line 29 to 10 or more seconds, or change the max_attempts on line 25 from 10 to e.g. 100.

The start-script doesn't seem to respect the timeout mechanism from systemd, that can be set via  `sudo systemctl edit influxdb.service`, the script could read this value and set max_attempts and/or the sleep value accordingly.
```
[Service]
TimeoutStartSec=15min
```

Kind regards,
Dennis

**Comment by lost-RD** [comment]
When can we expect an update for Raspbian systems? In the meantime I've upped my max-retries from 10 to 60.

**Comment by codyshepherd** [comment]
We will cut another rc release, 1.8.10rc1, within the next couple of weeks, and a full 1.8.10 release should follow soon after that.

**Comment by codyshepherd** [comment]
The 1.8.10rc1 build is now available. 

Find the deb for your architecture at https://dl.influxdata.com/influxdb/releases/influxdb_1.8.10rc1_< arch >.deb

The deb is available for `amd64`, `arm64`, `armel`, `armhf`, and `i386`

And the rpm at https://dl.influxdata.com/influxdb/releases/influxdb-1.8.10rc1.< arch >.rpm

The rpm is available for `x86_64`, `aarch64`, `armel`, `armv7hl`, and `i386`.

**Comment by s1shed** [comment]
> The 1.8.10rc1 build is now available.

Working in Raspbian, thanks. :)

**Comment by ToonSpinISAAC** [comment]
I have had to increase the `sleep` in our InfluxDB version 1.8.9 like @apenney-beeswax  has, or the systemd unit would keep restarting because the HTTP AI at port 8086 was not ready yet. In our case 30 seconds did the trick, but obviously a sleep is not the way to do this - maybe there should be two systemd units that depend on each other instead? That way one can wait for the other to be started before trying to start.

**Comment by robertpenz** [comment]
Same problem on Debian 10 (Buster) .. the sleep increase to 10 sec also helped on my setup.

**Comment by TKYAngus** [comment]
Same problem here after upgrading to 1.8.9 on CentOS 7.9, the sleep increase also helped

**Comment by significanter** [comment]
> Same problem on Debian 10 (Buster) .. the sleep increase to 10 sec also helped on my setup.

Another with the same system (Buster / 1.8.9) and same mitigation (increase to 10sec).
