### ISSUE TITLE
influx 2.0 restore fails with: invalid cross-device link

### ISSUE THREAD

**Issue by sahib** [influxdata/influxdb#22890]
__Steps to reproduce:__

1. Spin up Influx 2.1 with a docker-compose config entry like this:

```yaml
influx:
  image: influxdb:2.1.1-alpine
  restart: always
  environment:
    DOCKER_INFLUXDB_INIT_USERNAME: "admin"
    DOCKER_INFLUXDB_INIT_PASSWORD: "$password"
    DOCKER_INFLUXDB_INIT_ORG: "some-org"
    DOCKER_INFLUXDB_INIT_BUCKET: "initial"
    DOCKER_INFLUXDB_INIT_RETENTION: "4w"
    DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "$token"
    DOCKER_INFLUXDB_INIT_MODE: "upgrade"
  volumes:
    - "${my_data_folder}/influxdb:/var/lib/influxdb:rw"
    - "${my_config_folder}/influx/influxdb.conf:/etc/influxdb/influxdb.conf:ro"
    - "${my_data_folder}/influxdb2:/var/lib/influxdb2:rw"
    - "${my_config_folder}/influx2/config.toml:/etc/influxdb2/config.toml:ro"
  expose:
    - "8086"
```

2. Connect to the container with ``docker-compose exec influx sh``
3. Make a backup with ``influx backup --org some-org /tmp/backup``
4. Attempt to restore the backup:

```bash
2021/11/17 13:43:48 INFO: Restoring KV snapshot
2021/11/17 13:43:48 INFO: Restoring SQL snapshot
Error: failed to restore SQL snapshot: InfluxDB OSS-only command failed: 500 Internal Server Error: An internal error has occurred - check server logs
```

And the server logs say:

```bash
ts=2021-11-17T13:43:48.620552Z lvl=info msg="Resources opened" log_id=0XsY0eFW000 service=kvstore-bolt service="restored bolt" path=/var/lib/influxdb2/influxd.bolt.tmp
ts=2021-11-17T13:43:48.659097Z lvl=info msg="index opened with 8 partitions" log_id=0XsY0eFW000 service=storage-engine index=tsi
ts=2021-11-17T13:43:48.660690Z lvl=info msg="Reindexing TSM data" log_id=0XsY0eFW000 service=storage-engine engine=tsm1db_shard_id=34
ts=2021-11-17T13:43:48.660741Z lvl=info msg="Reindexing WAL data" log_id=0XsY0eFW000 service=storage-engine engine=tsm1db_shard_id=34
ts=2021-11-17T13:43:48.691339Z lvl=info msg="index opened with 8 partitions" log_id=0XsY0eFW000 service=storage-engine index=tsi
ts=2021-11-17T13:43:48.693861Z lvl=info msg="Reindexing TSM data" log_id=0XsY0eFW000 service=storage-engine engine=tsm1db_shard_id=35
ts=2021-11-17T13:43:48.694294Z lvl=info msg="Reindexing WAL data" log_id=0XsY0eFW000 service=storage-engine engine=tsm1db_shard_id=35
ts=2021-11-17T13:43:48.707817Z lvl=info msg="index opened with 8 partitions" log_id=0XsY0eFW000 service=storage-engine index=tsi
ts=2021-11-17T13:43:48.708433Z lvl=info msg="Reindexing TSM data" log_id=0XsY0eFW000 service=storage-engine engine=tsm1db_shard_id=2
ts=2021-11-17T13:43:48.708450Z lvl=info msg="Reindexing WAL data" log_id=0XsY0eFW000 service=storage-engine engine=tsm1db_shard_id=2
ts=2021-11-17T13:43:48.720990Z lvl=info msg="index opened with 8 partitions" log_id=0XsY0eFW000 service=storage-engine index=tsi
ts=2021-11-17T13:43:48.722198Z lvl=info msg="Reindexing TSM data" log_id=0XsY0eFW000 service=storage-engine engine=tsm1db_shard_id=20
ts=2021-11-17T13:43:48.722254Z lvl=info msg="Reindexing WAL data" log_id=0XsY0eFW000 service=storage-engine engine=tsm1db_shard_id=20
ts=2021-11-17T13:43:48.733144Z lvl=info msg="index opened with 8 partitions" log_id=0XsY0eFW000 service=storage-engine index=tsi
ts=2021-11-17T13:43:48.733755Z lvl=info msg="Reindexing TSM data" log_id=0XsY0eFW000 service=storage-engine engine=tsm1db_shard_id=21
ts=2021-11-17T13:43:48.733772Z lvl=info msg="Reindexing WAL data" log_id=0XsY0eFW000 service=storage-engine engine=tsm1db_shard_id=21
ts=2021-11-17T13:43:48.743264Z lvl=info msg="index opened with 8 partitions" log_id=0XsY0eFW000 service=storage-engine index=tsi
ts=2021-11-17T13:43:48.743797Z lvl=info msg="Reindexing TSM data" log_id=0XsY0eFW000 service=storage-engine engine=tsm1db_shard_id=25
ts=2021-11-17T13:43:48.743811Z lvl=info msg="Reindexing WAL data" log_id=0XsY0eFW000 service=storage-engine engine=tsm1db_shard_id=25
ts=2021-11-17T13:43:48.755871Z lvl=info msg="index opened with 8 partitions" log_id=0XsY0eFW000 service=storage-engine index=tsi
ts=2021-11-17T13:43:48.756455Z lvl=info msg="Reindexing TSM data" log_id=0XsY0eFW000 service=storage-engine engine=tsm1db_shard_id=31
ts=2021-11-17T13:43:48.756476Z lvl=info msg="Reindexing WAL data" log_id=0XsY0eFW000 service=storage-engine engine=tsm1db_shard_id=31
ts=2021-11-17T13:43:48.764186Z lvl=info msg="index opened with 8 partitions" log_id=0XsY0eFW000 service=storage-engine index=tsi
ts=2021-11-17T13:43:48.764677Z lvl=info msg="Reindexing TSM data" log_id=0XsY0eFW000 service=storage-engine engine=tsm1db_shard_id=32
ts=2021-11-17T13:43:48.764689Z lvl=info msg="Reindexing WAL data" log_id=0XsY0eFW000 service=storage-engine engine=tsm1db_shard_id=32
ts=2021-11-17T13:43:48.776011Z lvl=info msg="index opened with 8 partitions" log_id=0XsY0eFW000 service=storage-engine index=tsi
ts=2021-11-17T13:43:48.776557Z lvl=info msg="Reindexing TSM data" log_id=0XsY0eFW000 service=storage-engine engine=tsm1db_shard_id=33
ts=2021-11-17T13:43:48.776580Z lvl=info msg="Reindexing WAL data" log_id=0XsY0eFW000 service=storage-engine engine=tsm1db_shard_id=33
ts=2021-11-17T13:43:48.784401Z lvl=info msg="Resources opened" log_id=0XsY0eFW000 service=sqlite service="restored sqlite" path=/tmp/2397678724/influxd.sqlite
ts=2021-11-17T13:43:48.785063Z lvl=warn msg="internal error not returned to client" log_id=0XsY0eFW000 handler=error_logger error="rename /tmp/2397678724/influxd.sqlite /var/lib/influxdb2/influxd.sqlite: invalid cross-device link"
```

__Expected behavior:__

I expected the restore to work.

__Actual behavior:__

It stopped during importing the sqlite database. Seems like it does a ``os.Rename("/tmp/2397678724/influxd.sqlite", "/var/lib/influxdb2/influxd.sqlite"), which (as expected) fails since ``/tmp`` and ``/var/lib/influx2`` are on different block devices. Same would happen if done on the command-line with ``ln /tmp/some-file /var/lib/influxdb2/some-hardlink``. Note that this is not docker specific, it just happens regularly, since mounting a volume to ``/var/lib/influxdb2`` seems to be common practice. Writing the backup to e.g. ``/var/lib/influxdb2/backup`` also does not help, since the restore process still works with files in /tmp.

__Environment info:__

* System info: ``Linux 5.4.101-1-MANJARO x86_64``
* influxd version: ``InfluxDB 2.1.1 (git: 657e1839de) build_date: 2021-11-09T03:03:48Z``

**Comment by danxmoran** [comment]
[This](https://github.com/influxdata/influxdb/blob/dm-build-fixup-round-2/pkg/fs/fs_unix.go#L42-L44) is probably the function causing the error. It would need to be adjusted to detect when the source and destination are on separate devices and switch to a copy-then-delete-source strategy.

**Comment by abhi1693** [comment]
@danxmoran Any ETA on this? I have a production server that is down for 22 hours and I'm unable to restore data

**Comment by abhi1693** [comment]
I created a custom binary for myself based on the code from #22909 and the restore worked like a charm.

**Comment by MartinEmrich** [comment]
Just encountered this... if you need to restore now until the fix is released: point the `TMPDIR` environment variable for the server process to a directory on the same filesystem as the database (e.g. in /etc/default/influxdb2), restart server, then the restore succeeds.

**Comment by FuzzyMistborn** [comment]
@MartinEmrich can you explain a bit more what you mean?  Trying to restore a database and can't.

**Comment by MartinEmrich** [comment]
@FuzzyMistborn you need to set the environment variable `TMPDIR` to a directory on the same device/filesystem where also the influxdb Database files reside.

E.g. if your database is under /opt/influxdb on a separate partition mounted on /opt (which is IMHO good practice), you need to make a temporary directory e.g. /opt/temp, and set `TMPDIR=/opt/temp` for the influxdb server process.
This way, the move operations is within the same filesystem and will succeed.

**Comment by FuzzyMistborn** [comment]
Hmm....not sure how I would do this in Docker.  It's not a docker environment variable so I'd set it inside the container?

**Comment by pskomo** [comment]
Hi @MartinEmrich, any tips how to achieve it in docker? I'm using image influxdb:2.1.1 and bug still exists.

**Comment by MartinEmrich** [comment]
@pskomo I guess something like ` docker run  -e TMPDIR=/path/to/your/data/volume/somewhere`.
