### ISSUE TITLE
Use Balancer when choosing node for remote shard mapping

### ISSUE THREAD

**Issue by otoolep** [influxdata/influxdb#3377]
The existing Balancer code needs to be hooked up the Shard Mapper, so it intelligently chooses the target node.

**Comment by beckettsean** [comment]
@otoolep what's the status of this issue?

**Comment by otoolep** [comment]
Not yet implemented, though the core code exists and just needs to be ported to the distributed query code.

Currently when two remote nodes can service a query (assuming the local node cannot), the remote node is chosen at random, even if that randomly chosen node is down. This change will fix that and try the other node in that case. This is obviously a core part of HA queries.

No reason this can't be fixed in 0.9.4.

**Comment by Jhors2** [comment]
To be more specific, I think it would be ideal for the mapper to be intelligent enough to only pick nodes that have the latest timestamp for the data.  Meaning, if a node were to fail and come back, it should still not be chosen until hinted handoff catches it back up to the other nodes, this way data returned is always the latest most consistent data with the rest of the cluster.

**Comment by otoolep** [comment]
DQ support is not fully implemented yet, so this can be pushed out.

**Comment by toddboom** [comment]
Closing this out because it's no longer applicable.
