### ISSUE TITLE
[feature request] Auto alias using actual function call, e.g. `sum(value)` or `count(distinct(value))`

### ISSUE THREAD

**Issue by mikechack** [influxdata/influxdb#3838]
When doing a select such as `select sum(value), sum(value1)` the resulting response returns column names of `[sum,sum]`.

Grafana does not support the ability to specify alias on a per value basis when using structured query editor.

Returning an auto generated alias that is something like `<measurement>.<column name>` would definitively disambiguate the response.

**Comment by mikechack** [comment]
measurement.colname

Brackets got eaten in post.

**Comment by beckettsean** [comment]
similar to https://github.com/influxdb/influxdb/issues/3643, but slightly different behavior described.

This is a breaking change to the query return format and so will not be an 0.9 change.

**Comment by mikechack** [comment]
Thanks for the response. 

This could be addressed with Grafana changes, but I fear they would not be trivial additions to structured query editor. I think that much of the power of InfluxDB if negated when the response contains the same column name for distinctly different values. Any chance this might be considered in the future or should I look to requesting/making grafana enhancement request.

**Comment by beckettsean** [comment]
@mikechack this would be a breaking change to the API so it won't happen in the 0.9 lifecycle. There's no release estimate for 1.0 but it's at least a few months away.

**Comment by MikeSchroll** [comment]
Just to add to the discussion.. somewhere around this issue: https://github.com/influxdata/influxdb/issues/5679
it appears as though:
select sum(total) as TOTAL
changed from the column being named 'sum' to the column honoring AS and calling the column 'total'

(I experienced this behavior upgrading recently from 0.10 to 0.12 - but looks like it changed in 0.11)

This change may enable you to solve this problem using 'AS' even if it is not the default behavior.

**Comment by jsternberg** [comment]
Sorry that you never got a suitable response, but this isn't changeable now that we've gone to 1.0. We may revisit this when we look at what we want to change when we get to 2.0, but at the moment, I have to close it.

Sorry.

**Comment by beckettsean** [comment]
@jsternberg this is fixed, anyway. For a query like `select sum(value), sum(value1)` the output will be `sum_1` and `sum_2`.

**Comment by bogd** [comment]
I'm sorry, but I really don't see how that is "fixed". As I see it, the problem is that when you do `SELECT sum(value)`, the column alias is "sum". Which says absolutely nothing about the actual value you are reading, and makes grafana's $col alias pretty much useless.

Even if `sum(value), sum(value1)` now returns "sum_1, sum_2", that still does not describe the actual data in any meaningful way. 

I understand that changing this to a more meaningful format (such as sum.value, or value.sum) would be a major change, and for this reason the issue is unfixable as of now. But please don't call it "fixed"... :)
