### ISSUE TITLE
[repo] add support for raspbian

### ISSUE THREAD

**Issue by srsabu** [influxdata/influxdb#5112]
It would be great to have packages for raspbian on the Raspberry Pi.  It isn't difficult to compile but just adds another set of steps to get a new station up and running and then similar additional steps when upgrading.

**Comment by rossmcdonald** [comment]
@srsabu Thanks! We are planning on adding ARM builds to the repo shortly. I'll update this issue once it's done.

**Comment by nsteinmetz** [comment]
Also interested as I have some build issues with 0.10.0 as described in #5560

**Comment by s1m0** [comment]
Following #5330 the .deb packages are being built (since 0.10.0 beta2) but the package architecture is still "arm", not "armhf" so they won't install.

**Comment by rossmcdonald** [comment]
@s1m0 The next release should have the corrected architecture. In the meantime you should be able to install the `arm` architecture by using the following command:

```
dpkg --add-architecture arm
dpkg -i <package>
```

**Comment by s1m0** [comment]
Thanks @rossmcdonald that worked great - needed to be run as root - just in case anyone else comes this way...

**Comment by rossmcdonald** [comment]
@s1m0 Great, I'm glad that worked.

I also pushed some updates to the build script yesterday that fix this issue. `armhf` nightlies can be downloaded here:

https://s3.amazonaws.com/influxdb/influxdb_nightly_armhf.deb
https://s3.amazonaws.com/influxdb/influxdb-nightly.armhf.rpm

We'll also be providing official `armhf` packages for the next release as well. I'll close this issue once they are available through the stable channel of the repository.

**Comment by s1m0** [comment]
Thanks for the info., I installed the latest build without issues:-

||/ Name                          Version             Architecture        Description
+++-=============================-===================-===================-================================================================
ii  influxdb                      0.11.0~n1456560025- armhf               Distributed time-series database.


Regards,

Simon.

**Comment by s1m0** [comment]
Is anyone else having problems with the .influx_history file on the pi? 
The influx cli tool emits an error on every command:
```
There was an error writing history file: open : no such file or directory
```
the file exists and is owned by the pi user:-
```
-rw-r--r-- 1 pi   pi         27 Feb 22 17:07 .influx_history
```
I removed it and created an empty file using touch but I still get the same error. 
I'm using the latest nightly build.InfluxDB shell 0.11.0~n1456819234

**Comment by learnaddict** [comment]
I've installed version 0.10.3 on a Raspberry Pi and seeing the issue as well, using https://s3.amazonaws.com/influxdb/influxdb-0.10.3-1_linux_arm.tar.gz

The history file is not being created at all.

I captured the strace output using `strace -ffttTo /tmp/strace.out influx` and executed `show databases` in the client. This is the output from `grep ENOENT /tmp/strace.out*`

```
/tmp/strace.out.2423:13:26:33.205952 open("", O_RDWR|O_CREAT|O_TRUNC|O_LARGEFILE|O_CLOEXEC, 0666) = -1 ENOENT (No such file or directory) <0.000065>
/tmp/strace.out.2423:13:26:35.244640 open("", O_RDWR|O_CREAT|O_TRUNC|O_LARGEFILE|O_CLOEXEC, 0666) = -1 ENOENT (No such file or directory) <0.000061>
/tmp/strace.out.2423:13:26:35.245781 open("", O_RDWR|O_CREAT|O_TRUNC|O_LARGEFILE|O_CLOEXEC, 0666) = -1 ENOENT (No such file or directory) <0.000059>
```

Is the filename that influx in trying to open an empty string/null?

**Comment by rossmcdonald** [comment]
I've opened another issue for tracking of the `error writing history` problem on ARM [here](https://github.com/influxdata/influxdb/issues/6070), and will be closing this issue now that ARM builds have been added to the repository.
