### ISSUE TITLE
[1.2.0] Segment violation in models.Tags.Get

### ISSUE THREAD

**Issue by nimdanitro** [influxdata/influxdb#8022]
version 1.2.0, branch master, commit b7bb7e8359642b6e071735b50ae41f5eb343fd42

Not related to subqueries. It looks like this panic was triggered by a continuous query. 

```
unexpected fault address 0x7f0075f5a764
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f0075f5a764 pc=0x45fd12]

goroutine 5477123 [running]:
runtime.throw(0xab4597, 0x5)
        /opt/OSAGgobuild/src/runtime/panic.go:566 +0x95 fp=0xc55c3d5400 sp=0xc55c3d53e0
runtime.sigpanic()
        /opt/OSAGgobuild/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc55c3d5458 sp=0xc55c3d5400
runtime.memeqbody()
        /opt/OSAGgobuild/src/runtime/asm_amd64.s:1451 +0x112 fp=0xc55c3d5460 sp=0xc55c3d5458
github.com/influxdata/influxdb/models.Tags.Get(0xc4583ab420, 0x4, 0x4, 0xc55c3d5570, 0x4, 0x20, 0xc4d6687681, 0xc4d6687680, 0x0)
        /usr/src/packages/src/OSAGinfluxdb/src/github.com/influxdata/influxdb/models/points.go:1710 +0xf4 fp=0xc55c3d5528 sp=0xc55c3d5460
github.com/influxdata/influxdb/models.Tags.GetString(0xc4583ab420, 0x4, 0x4, 0xc476857b30, 0x4, 0x0, 0x0)
        /usr/src/packages/src/OSAGinfluxdb/src/github.com/influxdata/influxdb/models/points.go:1719 +0x8f fp=0xc55c3d55a0 sp=0xc55c3d5528
github.com/influxdata/influxdb/tsdb.(*Measurement).TagSets(0xc45f3134a0, 0x473, 0xc5bae4ae80, 0x6, 0x8, 0xe2fba0, 0xc4b37fb9e0, 0xc64da78660, 0x26, 0xc64da785d0, ...)
        /usr/src/packages/src/OSAGinfluxdb/src/github.com/influxdata/influxdb/tsdb/meta.go:807 +0x291 fp=0xc55c3d58f8 sp=0xc55c3d55a0
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createCallIterator(0xc4200ce900, 0xc658480560, 0x14, 0xc4b37fbb30, 0xe2fc20, 0xc4b37fbb30, 0xe76698, 0x0, 0x0, 0x0, ...)
        /usr/src/packages/src/OSAGinfluxdb/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1281 +0x110 fp=0xc55c3d59b8 sp=0xc55c3d58f8
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).CreateIterator(0xc4200ce900, 0xc658480560, 0x14, 0xe2fc20, 0xc4b37fbb30, 0xe76698, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/src/packages/src/OSAGinfluxdb/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1256 +0x102 fp=0xc55c3d5bf8 sp=0xc55c3d59b8
github.com/influxdata/influxdb/tsdb.(*Shard).CreateIterator(0xc420452580, 0xc658480560, 0x14, 0xe2fc20, 0xc4b37fbb30, 0xe76698, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/src/packages/src/OSAGinfluxdb/src/github.com/influxdata/influxdb/tsdb/shard.go:694 +0xd1 fp=0xc55c3d5d28 sp=0xc55c3d5bf8
github.com/influxdata/influxdb/tsdb.Shards.CreateIterator(0xc60c91cc40, 0x1, 0x1, 0xc658480560, 0x14, 0xe2fc20, 0xc4b37fbb30, 0xe76698, 0x0, 0x0, ...)
        /usr/src/packages/src/OSAGinfluxdb/src/github.com/influxdata/influxdb/tsdb/shard.go:1008 +0xfd fp=0xc55c3d5ed8 sp=0xc55c3d5d28
github.com/influxdata/influxdb/tsdb.(*Shards).CreateIterator(0xc6584816c0, 0xc658480560, 0x14, 0xe2fc20, 0xc4b37fbb30, 0xe76698, 0x0, 0x0, 0x0, 0x0, ...)
        <autogenerated>:54 +0xc9 fp=0xc55c3d6018 sp=0xc55c3d5ed8
github.com/influxdata/influxdb/coordinator.(*LocalShardMapping).CreateIterator(0xc60c91cc38, 0xc510132b80, 0xe2fc20, 0xc4b37fbb30, 0xe76698, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/src/packages/src/OSAGinfluxdb/src/github.com/influxdata/influxdb/coordinator/shard_mapper.go:169 +0x330 fp=0xc55c3d61b8 sp=0xc55c3d6018
github.com/influxdata/influxdb/influxql.(*exprIteratorBuilder).buildCallIterator.func1.1(0xc55c3d6ed0, 0xc55c3d65e0, 0xc4b37fbb30, 0xc475e4f860, 0x0)
        /usr/src/packages/src/OSAGinfluxdb/src/github.com/influxdata/influxdb/influxql/select.go:799 +0x171 fp=0xc55c3d6398 sp=0xc55c3d61b8
github.com/influxdata/influxdb/influxql.(*exprIteratorBuilder).buildCallIterator.func1(0xc4b37fbb30, 0xc55c3d6ed0, 0xc, 0xc67a4ab740, 0x0, 0x0)
        /usr/src/packages/src/OSAGinfluxdb/src/github.com/influxdata/influxdb/influxql/select.go:827 +0x7eb fp=0xc55c3d67d8 sp=0xc55c3d6398
github.com/influxdata/influxdb/influxql.(*exprIteratorBuilder).buildCallIterator(0xc55c3d6ed0, 0xc4b37fbb30, 0x0, 0x3, 0x6, 0x0)
        /usr/src/packages/src/OSAGinfluxdb/src/github.com/influxdata/influxdb/influxql/select.go:933 +0x8f fp=0xc55c3d6d70 sp=0xc55c3d67d8
github.com/influxdata/influxdb/influxql.buildExprIterator(0xe2fc20, 0xc4b37fbb30, 0x7ef72c942470, 0xc60c91cc38, 0xc475e4ee60, 0x1, 0x1, 0xe2fc20, 0xc4b37fbb30, 0xe76698, ...)
        /usr/src/packages/src/OSAGinfluxdb/src/github.com/influxdata/influxdb/influxql/select.go:408 +0x497 fp=0xc55c3d6ff8 sp=0xc55c3d6d70
github.com/influxdata/influxdb/influxql.buildFieldIterators.func1(0xc475e4ed70, 0x2, 0x2, 0x7ef72c942470, 0xc60c91cc38, 0xc475e4ee60, 0x1, 0x1, 0xc55c3d7350, 0x412000, ...)
        /usr/src/packages/src/OSAGinfluxdb/src/github.com/influxdata/influxdb/influxql/select.go:344 +0x1a9 fp=0xc55c3d71c0 sp=0xc55c3d6ff8
github.com/influxdata/influxdb/influxql.buildFieldIterators(0xc475e4ed70, 0x2, 0x2, 0x7ef72c942470, 0xc60c91cc38, 0xc475e4ee60, 0x1, 0x1, 0x0, 0x0, ...)
        /usr/src/packages/src/OSAGinfluxdb/src/github.com/influxdata/influxdb/influxql/select.go:379 +0x10f fp=0xc55c3d7310 sp=0xc55c3d71c0
github.com/influxdata/influxdb/influxql.buildIterators(0xc4de272380, 0x7ef72c942470, 0xc60c91cc38, 0x0, 0x0, 0xe76698, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/src/packages/src/OSAGinfluxdb/src/github.com/influxdata/influxdb/influxql/select.go:99 +0x50c fp=0xc55c3d7640 sp=0xc55c3d7310
github.com/influxdata/influxdb/influxql.Select(0xc4de272380, 0x7ef72c942470, 0xc60c91cc38, 0xc4e91ebdb0, 0xc60c91cc38, 0x0, 0xc60c91cc38, 0x0, 0x0)
        /usr/src/packages/src/OSAGinfluxdb/src/github.com/influxdata/influxdb/influxql/select.go:40 +0xee fp=0xc55c3d7860 sp=0xc55c3d7640
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).createIterators(0xc4203d6700, 0xc4de2722a0, 0xc55c3d7c68, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/src/packages/src/OSAGinfluxdb/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:597 +0x5c9 fp=0xc55c3d79c8 sp=0xc55c3d7860
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).executeSelectStatement(0xc4203d6700, 0xc4de2721c0, 0xc55c3d7c68, 0x0, 0x0)
        /usr/src/packages/src/OSAGinfluxdb/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:433 +0x75 fp=0xc55c3d7b60 sp=0xc55c3d79c8
github.com/influxdata/influxdb/coordinator.(*StatementExecutor).ExecuteStatement(0xc4203d6700, 0xe334a0, 0xc4de2721c0, 0x0, 0x371, 0xc623cb2ae0, 0xc623cb2960, 0xe36b60, 0xc4203e5e60, 0xc623cb2a20, ...)
        /usr/src/packages/src/OSAGinfluxdb/src/github.com/influxdata/influxdb/coordinator/statement_executor.go:57 +0x2afc fp=0xc55c3d7c50 sp=0xc55c3d7b60
github.com/influxdata/influxdb/influxql.(*QueryExecutor).executeQuery(0xc4203d9440, 0xc658480ae0, 0xc420303ca0, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc623cb2900, ...)
        /usr/src/packages/src/OSAGinfluxdb/src/github.com/influxdata/influxdb/influxql/query_executor.go:312 +0x55d fp=0xc55c3d7f38 sp=0xc55c3d7c50
runtime.goexit()
        /opt/OSAGgobuild/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc55c3d7f40 sp=0xc55c3d7f38
created by github.com/influxdata/influxdb/influxql.(*QueryExecutor).ExecuteQuery
        /usr/src/packages/src/OSAGinfluxdb/src/github.com/influxdata/influxdb/influxql/query_executor.go:207 +0xb5
```

**Comment by jwilder** [comment]
Fixed in 1.1 via #8027.  Fixed in 1.2 via #8038.

**Comment by jwilder** [comment]
This may not be fixed in 1.2.  Re-opening to track other instances.

**Comment by mathfool** [comment]
I've encounter the same issue

`unexpected fault address 0x7faaeb0228c7
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7faaeb0228c7 pc=0x460f71]

goroutine 18293588 [running]:
runtime.throw(0xab4597, 0x5)
        /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc5bb82ec30 sp=0xc5bb82ec10
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc5bb82ec88 sp=0xc5bb82ec30
runtime.memmove(0xc5da9fa760, 0x7faaeb0228c7, 0xd)
        /usr/local/go/src/runtime/memmove_amd64.s:164 +0x371 fp=0xc5bb82ec90 sp=0xc5bb82ec88
runtime.slicebytetostring(0x0, 0x7faaeb0228c7, 0xd, 0x1e7a9b, 0xc5816201b0, 0xe34780)
        /usr/local/go/src/runtime/string.go:94 +0x7e fp=0xc5bb82ece8 sp=0xc5bb82ec90
github.com/influxdata/influxdb/models.Tags.Map(0xc435677ce0, 0x4, 0x4, 0xc435677ce0)
        /root/go/src/github.com/influxdata/influxdb/models/points.go:1755 +0x10f fp=0xc5bb82edd0 sp=0xc5bb82ece8
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createVarRefSeriesIterator(0xc42041e6c0, 0xc4768a7e20, 0xc42034a900, 0xc432f69310, 0x4d, 0xc6635623c0, 0x0, 0x0, 0xe75698, 0x0, ...)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1468 +0xc1 fp=0xc5bb82fbd0 sp=0xc5bb82edd0
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createTagSetGroupIterators(0xc42041e6c0, 0xc4768a7e20, 0xc42034a900, 0xc55e06b6c0, 0xac, 0xc94, 0xc6635623c0, 0xc485f536c0, 0xac, 0xc94, ...)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1455 +0x20d fp=0xc5bb82fdc8 sp=0xc5bb82fbd0
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createTagSetIterators.func1(0xc45e3445d0, 0xc5652f4000, 0x20, 0x20, 0xc42041e6c0, 0xc4768a7e20, 0xc42034a900, 0xc6635623c0, 0xc71fe30690, 0x11)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1410 +0x12d fp=0xc5bb82ff50 sp=0xc5bb82fdc8
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc5bb82ff58 sp=0xc5bb82ff50
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createTagSetIterators
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1411 +0x3c3`

**Comment by mathfool** [comment]
I've upgrade to 1.2.2, still encounter segmentation fault, and from the log I didn't find a continuous query prior to the panic:

`
�
[httpd] 10.22.22.43 - - [24/Mar/2017:21:29:56 -0400] "POST /write?consistency=&db=realtime&precision=ms&rp= HTTP/1.1" 204 0 "-" "InfluxDBClient" 8e005568-10fa-11e7-bddd-000000000000 2294
[httpd] 10.22.22.43 - - [24/Mar/2017:21:29:56 -0400] "POST /write?consistency=&db=system&precision=ns&rp= HTTP/1.1" 204 0 "-" "InfluxDBClient" 8e00bc50-10fa-11e7-bdde-000000000000 1624
[httpd] 10.22.22.43 - - [24/Mar/2017:21:29:56 -0400] "POST /write?consistency=&db=inventory&precision=ms&rp= HTTP/1.1" 204 0 "-" "InfluxDBClient" 8e0108bf-10fa-11e7-bddf-000000000000 1873
unexpected fault address 0x7f3858d7084a
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f3858d7084a pc=0x460f71]

goroutine 5080950 [running]:
runtime.throw(0xab6f37, 0x5)
        /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc58df3abb8 sp=0xc58df3ab98
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc58df3ac10 sp=0xc58df3abb8
runtime.memmove(0xc422a1ddc0, 0x7f3858d7084a, 0xd)
        /usr/local/go/src/runtime/memmove_amd64.s:164 +0x371 fp=0xc58df3ac18 sp=0xc58df3ac10
github.com/influxdata/influxdb/models.Tags.Clone(0xc42391eb40, 0x4, 0x4, 0x608efe, 0xc42958e460, 0xc58df3ada8)
        /root/go/src/github.com/influxdata/influxdb/models/points.go:1685 +0x1f4 fp=0xc58df3ad58 sp=0xc58df3ac18
github.com/influxdata/influxdb/tsdb.(*Series).Tags(0xc4323cf180, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/tsdb/meta.go:1639 +0x96 fp=0xc58df3ad98 sp=0xc58df3ad58
github.com/influxdata/influxdb/tsdb.(*DatabaseIndex).TagsForSeries(0xc420292f00, 0xc431ec7c70, 0x4e, 0x0, 0x0, 0x0)
        /root/go/src/github.com/influxdata/influxdb/tsdb/meta.go:277 +0xbe fp=0xc58df3add0 sp=0xc58df3ad98
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createVarRefSeriesIterator(0xc420334ea0, 0xc57a9b72a0, 0xc420dc2a20, 0xc431ec7c70, 0x4e, 0xc5cbd8dea0, 0x0, 0x0, 0xc47a860440, 0x0, ...)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1517 +0x9f fp=0xc58df3bbd0 sp=0xc58df3add0
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createTagSetGroupIterators(0xc420334ea0, 0xc57a9b72a0, 0xc420dc2a20, 0xc4ec53d5d0, 0x29, 0x393, 0xc5cbd8dea0, 0xc4ec5444d0, 0x29, 0x393, ...)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1504 +0x20d fp=0xc58df3bdc8 sp=0xc58df3bbd0
github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createTagSetIterators.func1(0xc4402a1c60, 0xc45d842200, 0x20, 0x20, 0xc420334ea0, 0xc57a9b72a0, 0xc420dc2a20, 0xc5cbd8dea0, 0xc4e08d9680, 0x15)
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1459 +0x12d fp=0xc58df3bf50 sp=0xc58df3bdc8
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc58df3bf58 sp=0xc58df3bf50
created by github.com/influxdata/influxdb/tsdb/engine/tsm1.(*Engine).createTagSetIterators
        /root/go/src/github.com/influxdata/influxdb/tsdb/engine/tsm1/engine.go:1460 +0x3c3
`

**Comment by jwilder** [comment]
Fixed via #8192.

**Comment by micastle** [comment]
is the crash in models.Tags.Map fixed? I got the same issue on windows with v1.2.0
